### ISSUE TITLE
Print overall statistics 

### ISSUE THREAD

**Issue by cedrusx** [pamela-project/slambench#29] opened 2019-06-12 09:14 UTC

**Comment by bbodin** [comment] 2019-06-14 00:00
Thanks for your comment. This is in the roadmap (issue Duplicate of #19).

**Closed as completed by bbodin** 2019-06-14 00:00 UTC
Labels: duplicate

**Comment by cedrusx** [comment] 2019-06-14 12:25
Sorry Bruno, this issue was posted by a mistake -- I did not even noticed it had been posted. My apologies.
